server:
  port: 10010  # 网关端口
spring:
  application:
    name: gateway  # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848  # nacos地址
    #      server-addr: localhost:80  # nacos地址
    gateway:
      routes:  # 网关路由配置
        - id: user-service  # 路由id
          uri: lb://user-service  # 路由目标地址， lb代表负载均衡
          predicates:  # 路由条件，也就是只有满足条件的请求才会被路由到目标地址
            - Path=/user/**
        - id: upload-service  # 路由id
          uri: lb://upload-service  # 路由目标地址， lb代表负载均衡
          predicates: # 路由条件，也就是只有满足条件的请求才会被路由到目标地址
            - Path=/upload/**
        - id: article-service  # 路由id
          uri: lb://article-service  # 路由目标地址， lb代表负载均衡
          predicates: # 路由条件，也就是只有满足条件的请求才会被路由到目标地址
            - Path=/article/**
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/order/**
#          filters:  # 过滤器
#            - AddRequestHeader=hello, world  # 添加请求头 hello=world
      default-filters:  # 全局过滤器

      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://127.0.0.1:8080"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
eblog:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: akiey
    # 设置jwt过期时间24小时
    user-ttl: 86400000
    # 设置前端传递过来的令牌名称
    user-token-name: token