server:
  port: 8082
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eblog
    username: root
    password: 123456
feign:
  client:
    config:
      default:  # 全局
        loggerLevel: BASIC  # 日志级别
  httpclient:
    enabled: true  # 支持httpclient的开关
    max-connections: 200  # 最大连接数
    max-connections-per-route: 50  # 单个路径的最大连接数